spring.application.name=java-backend
server.address=0.0.0.0
server.port=9090

# PostgreSQL Database Configuration
spring.datasource.url=${PSQL_DB_HOST_URL}
spring.datasource.username=${PSQL_DB_USERNAME}
spring.datasource.password=${PSQL_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.open-in-view=false


#spring emailer
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_FROM}
spring.mail.password=${MAIL_PASS}
# spring.mail.protocol=smtp

# Authentication and security settings
spring.mail.properties.mail.smtp.auth=true

# These two are **needed** for SSL on port 587, and not for 465
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# These two are **needed** for SSL on port 465, and not for 587
# spring.mail.properties.mail.smtp.ssl.enable=true
# spring.mail.properties.mail.smtp.ssl.trust=smtp.zoho.in

# spring.mail.properties.mail.smtp.socketFactory.port=465
# spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
# spring.mail.properties.mail.smtp.socketFactory.fallback=false

